### ISSUE TITLE
New Curseforge Website

### ISSUE THREAD

**Issue by NielsPilgaard** [TheRandomLabs/ChangelogGenerator#18]
Hey o/

I just thought I'd let you know that since the Curseforge website update, project IDs seem to have shifted somehow, or possibly the API to access them? Either way, I have not been able to get the ChangelogGenerator to work.

```
Exert of stacktrace:

com.therandomlabs.curseapi.project.InvalidProjectIDException: Project with ID 314002 not found
        at com.therandomlabs.curseapi.CurseForge.lambda$fromIDNoValidation$1(CurseForge.java:240)
        at com.therandomlabs.curseapi.CurseAPI.actuallyDoWithRetries(CurseAPI.java:159)
        at com.therandomlabs.curseapi.CurseAPI.doWithRetries(CurseAPI.java:140)
        at com.therandomlabs.curseapi.CurseForge.fromIDNoValidation(CurseForge.java:235)
        at com.therandomlabs.curseapi.CurseForge.fromID(CurseForge.java:213)
        at com.therandomlabs.curseapi.project.CurseProject.<init>(CurseProject.java:142)
        at com.therandomlabs.curseapi.project.CurseProject.fromID(CurseProject.java:860)
        at com.therandomlabs.curseapi.minecraft.modpack.Mod.title(Mod.java:97)
        at com.therandomlabs.curseapi.minecraft.modpack.comparison.ModListComparison.lambda$loadModInfo$0(ModListCompari
```

**Comment by TheRandomLabs** [comment]
Yeah, I'm aware. I'll fix this soon.

**Comment by NielsPilgaard** [comment]
Thanks!
