### ISSUE TITLE
Appears to not work after latest Curseforge (API?) update.

### ISSUE THREAD

**Issue by MsVoxxie** [TheRandomLabs/ChangelogGenerator#31]
Getting this error on the latest jar build.

Exception in thread "main" java.lang.NullPointerException
        at com.therandomlabs.curseapi.minecraft.modpack.MinecraftInfo.forgeVersion(MinecraftInfo.java:62)
        at com.therandomlabs.curseapi.minecraft.modpack.ExMPManifest.forgeVersion(ExMPManifest.java:155)
        at com.therandomlabs.curseapi.minecraft.modpack.MPManifest.modList(MPManifest.java:207)
        at com.therandomlabs.curseapi.minecraft.modpack.ExMPManifest.universalFiles(ExMPManifest.java:105)
        at com.therandomlabs.curseapi.minecraft.modpack.MPManifest.getAllFiles(MPManifest.java:106)
        at com.therandomlabs.changeloggenerator.ChangelogGenerator.run(ChangelogGenerator.java:107)
        at com.therandomlabs.changeloggenerator.ChangelogGenerator.main(ChangelogGenerator.java:74)

**Comment by TheRandomLabs** [comment]
You seem to be on quite an old version of ChangelogGenerator. Can you try updating?

**Comment by MsVoxxie** [comment]
> You seem to be on quite an old version of ChangelogGenerator. Can you try updating?

Really? That was the latest download, ill check again now.

Also sorry for the long delay.

**Comment by MsVoxxie** [comment]
![b267BM](https://user-images.githubusercontent.com/10318911/104785861-92b56780-5759-11eb-8e01-5773122e63a2.png)
Same issue. However, the old 2.0.0-pre3 oddly work still.

**Comment by TheRandomLabs** [comment]
The pre-release *is* the new version.
