### ISSUE TITLE
Crashes on Linux

### ISSUE THREAD

**Issue by kreezxil** [TheRandomLabs/ChangelogGenerator#33]
ByteCodeViewer shows that your internal changelog says this was last updated for 1.12.2. Which might be part of the problem as I generated this with 1.16.4 manifests.

| file | gist |
| - | - |
| new.json | https://gist.github.com/cc847fd01f1911ffc84d5ccbbc524f15 |
| old.json | https://gist.github.com/7c765a3339e374178bb9ce701b9d1de0 |

```bash
$ java -jar ChangelogGenerator.jar 
Exception in thread "main" java.lang.NullPointerException
        at com.therandomlabs.curseapi.minecraft.modpack.MinecraftInfo.forgeVersion(MinecraftInfo.java:62)
        at com.therandomlabs.curseapi.minecraft.modpack.ExMPManifest.forgeVersion(ExMPManifest.java:155)
        at com.therandomlabs.curseapi.minecraft.modpack.MPManifest.modList(MPManifest.java:207)
        at com.therandomlabs.curseapi.minecraft.modpack.ExMPManifest.universalFiles(ExMPManifest.java:105)
        at com.therandomlabs.curseapi.minecraft.modpack.MPManifest.getAllFiles(MPManifest.java:106)
        at com.therandomlabs.changeloggenerator.ChangelogGenerator.run(ChangelogGenerator.java:107)
        at com.therandomlabs.changeloggenerator.ChangelogGenerator.main(ChangelogGenerator.java:74)
```
```
$ java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
```
```
$ ls *.json
new.json  old.json
```

System Information:
```
Operating System: Manjaro Linux
KDE Plasma Version: 5.20.4
KDE Frameworks Version: 5.77.0
Qt Version: 5.15.2
Kernel Version: 5.10.2-2-MANJARO
OS Type: 64-bit
Processors: 8 × AMD FX(tm)-8350 Eight-Core Processor
Memory: 23.5 GiB of RAM
Graphics Processor: GeForce GTX 750 Ti/PCIe/SSE2
```

**Comment by TheRandomLabs** [comment]
The latest release no longer works. The pre-release is the one you should use. This will be clearer once I get around to finishing 2.0.0.
