### ISSUE TITLE
No longer works? 

### ISSUE THREAD

**Issue by evanbones** [TheRandomLabs/ChangelogGenerator#37]
I'm using the latest version, and the program fails to load

com.therandomlabs.curseapi.CurseException: Failed to read JSON: old.json
        at com.therandomlabs.curseapi.util.MoshiUtils.fromJSON(MoshiUtils.java:88)
        at com.therandomlabs.curseapi.minecraft.modpack.CurseModpack.fromJSON(CurseModpack.java:183)
        at com.therandomlabs.changeloggenerator.Main.run(Main.java:127)
        at com.therandomlabs.changeloggenerator.ChangelogGeneratorOptions.call(ChangelogGeneratorOptions.java:105)
        at com.therandomlabs.changeloggenerator.ChangelogGeneratorOptions.call(ChangelogGeneratorOptions.java:35)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at com.therandomlabs.changeloggenerator.Main.main(Main.java:58)
Caused by: java.nio.file.NoSuchFileException: old.json
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
        at java.base/java.nio.file.Files.newInputStream(Files.java:156)
        at okio.Okio.source(Okio.java:182)
        at com.therandomlabs.curseapi.util.MoshiUtils.fromJSON(MoshiUtils.java:85)
        ... 12 more

**Comment by TheRandomLabs** [comment]
Does `old.json` exist?

**Comment by evanbones** [comment]
Wait I'm stupid, I had it in the wrong folder! Sorry!
