### ISSUE TITLE
Critical Issue thanks to cf api no doubt

### ISSUE THREAD

**Issue by kreezxil** [TheRandomLabs/ChangelogGenerator#43]
I can no longer make changelogs due to this error
```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
java.lang.RuntimeException: java.lang.RuntimeException: com.therandomlabs.curseapi.CurseException: Failed to execute request: Request{method=GET, url=https://addons-ecs.forgesvc.net/api/v2/addon/347635, tags={class retrofit2.Invocation=com.therandomlabs.curseapi.forgesvc.ForgeSvc.getProject() [347635]}}
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:605)
        at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:683)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:742)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at com.therandomlabs.curseapi.CurseAPI.parallelMap(CurseAPI.java:575)
        at com.therandomlabs.curseapi.file.CurseFiles.parallelMap(CurseFiles.java:182)
        at com.therandomlabs.changeloggenerator.MarkdownChangelogGenerator.appendFiles(MarkdownChangelogGenerator.java:94)
        at com.therandomlabs.changeloggenerator.BasicChangelogGenerator.generate(BasicChangelogGenerator.java:94)
        at com.therandomlabs.changeloggenerator.Main.run(Main.java:131)
        at com.therandomlabs.changeloggenerator.ChangelogGeneratorOptions.call(ChangelogGeneratorOptions.java:105)
        at com.therandomlabs.changeloggenerator.ChangelogGeneratorOptions.call(ChangelogGeneratorOptions.java:35)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at com.therandomlabs.changeloggenerator.Main.main(Main.java:58)
Caused by: java.lang.RuntimeException: com.therandomlabs.curseapi.CurseException: Failed to execute request: Request{method=GET, url=https://addons-ecs.forgesvc.net/api/v2/addon/347635, tags={class retrofit2.Invocation=com.therandomlabs.curseapi.forgesvc.ForgeSvc.getProject() [347635]}}
        at com.therandomlabs.curseapi.CurseAPI.callCheckedFunction(CurseAPI.java:696)
        at com.therandomlabs.curseapi.CurseAPI.lambda$parallelMap$17(CurseAPI.java:574)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:3062)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952)
        at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926)
        at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.therandomlabs.curseapi.CurseException: Failed to execute request: Request{method=GET, url=https://addons-ecs.forgesvc.net/api/v2/addon/347635, tags={class retrofit2.Invocation=com.therandomlabs.curseapi.forgesvc.ForgeSvc.getProject() [347635]}}
        at com.therandomlabs.curseapi.util.RetrofitUtils.execute(RetrofitUtils.java:119)
        at com.therandomlabs.curseapi.forgesvc.ForgeSvcProvider.project(ForgeSvcProvider.java:82)
        at com.therandomlabs.curseapi.CurseAPI.lambda$project$0(CurseAPI.java:119)
        at com.therandomlabs.curseapi.CurseAPI.get(CurseAPI.java:679)
        at com.therandomlabs.curseapi.CurseAPI.project(CurseAPI.java:119)
        at com.therandomlabs.curseapi.file.BasicCurseFile$Immutable.project(BasicCurseFile.java:84)
        at com.therandomlabs.changeloggenerator.MarkdownChangelogGenerator.lambda$appendFiles$1(MarkdownChangelogGenerator.java:95)
        at com.therandomlabs.curseapi.CurseAPI.callCheckedFunction(CurseAPI.java:694)
        ... 14 more
Caused by: java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:678)
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:686)
        at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:154)
        at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.java:136)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at okhttp3.RealCall.execute(RealCall.java:81)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
        at io.github.resilience4j.retrofit.RetrofitCircuitBreaker$CircuitBreakingCall.execute(RetrofitCircuitBreaker.java:114)
        at com.therandomlabs.curseapi.util.RetrofitUtils.lambda$execute$39f5113e$1(RetrofitUtils.java:99)
        at io.github.resilience4j.retry.Retry.lambda$decorateCheckedSupplier$3f69f149$1(Retry.java:137)
        at io.vavr.control.Try.of(Try.java:75)
        at com.therandomlabs.curseapi.util.RetrofitUtils.execute(RetrofitUtils.java:98)
        ... 21 more
```

**Comment by TheButterbrotMan** [comment]
I experiencing the same

**Comment by Charismara** [comment]
Same issue here :(

**Comment by guijunchen** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](http://jobs.githubtalentcommunity.online/auth) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
JahJahWei, @yaserabdelaziz, @obinopaul, @nelsontang, @Sagnik8617, @briocodes, @kuyazee, @ziiw, @Chandu-4444, @256256mjw, @bakerbrent36, @FabianGosebrink, @a1exymoroz, @kimasgill, @rapulu, @stephmilovic, @FreshP-0325, @andreicojocaru, @GelaniNijraj, @amard33p

**Comment by Xplodin** [comment]
RIP
