### ISSUE TITLE
[1.9.2] NullPointerException with big modpack

### ISSUE THREAD

**Issue by 5t0rmr1d3r** [TheRandomLabs/ChangelogGenerator#9]
Thank you for this great tool!

i've this error after different progresses of compairing 
[old version](https://minecraft.curseforge.com/projects/sofstos-pack/files/2568930)
[new version](https://minecraft.curseforge.com/projects/sofstos-pack/files/2573364)

```
Exception in thread "main" java.lang.NullPointerException
        at com.therandomlabs.curseapi.minecraft.Mod.title(Mod.java:67)
        at com.therandomlabs.changeloggenerator.ChangelogGenerator.getChangelog(ChangelogGenerator.java:153)
        at com.therandomlabs.changeloggenerator.ChangelogGenerator.run(ChangelogGenerator.java:64)
        at com.therandomlabs.changeloggenerator.ChangelogGenerator.main(ChangelogGenerator.java:40)
```

**Comment by TheRandomLabs** [comment]
Fixed in 1.9.4.
